language: java
install: mvn install -DskipTests=true -Dcobertura.skip  -Dmaven.javadoc.skip=true
  -B -V
deploy:
  provider: script
  script: bash ./deploy.sh
  skip_cleanup: true
AWS_SECRET_KEY=CamnA/H2SIIMhUu5VYKWp4fnZaQfbejsVWgJCimj:
  secure: hIG92nLmMkOzUtuAeoG+KarxF4Lythfy4SIjVvSUqzpoVz94vn0tV303h4nHvY0vTltBwNIX2OwUPyIy/Bxs2nxThnVJi3jId09DwD429tSf0Ie8/oYRmnELI4QFiRDDqxVQ0eQrltf/ilEHdTFbSuzNALMrW4nlFX4rt2uRJvQKLn9MR/8NoQqQrWQcQYSQALNyfBOA1zCopF7sXRvBtB8pddh207UbRhnBwBCVHlH8EsbbGD0qe9csjiE2I7P5viVizHRC67nIz9bviMxeCUQlc4aYlWmVHhQ64gI4xNNb7mu4Vne/pWAi1qG/8ebMybSk2n8FXdkZaGAqSwBgYW9GuYiQhwUwNswnUw3eOmMe2Y04gWw858x7pT800J9j0xt7JgdsmsB9AYi8UUVnicOP1yZyW3YbJAabRFVvVQyt2eE/CkK3AXdVd+zKHtJv55U+D9NnbdH6RTeIRi7G6xtH0rmt1114lPNOlCShHwVy/Bg5VyM5knzSaF9VwjasR3BsctM39SF7XJSqWp+C9u+f/pIU5pwW0k6xR2N4LE1pi9CD9aUbjnUobayg4xyY1gQSwBP4eyuE/wRz+5QdyF5z6+63P+H143A5LiIGdJZ8Nbagt0Eds/EoHJ0xe6aUjed14UB3zrm1EUv7B1dsHDrkX0ioDm7kt7HzbtJHnSM=
